### ISSUE TITLE
Snapshot with high resolution starts shows the same still image after a while

### ISSUE THREAD

**Issue by aalbul** [roleoroleo/yi-hack-Allwinner#46]
Hello,
Thanks for a great work on hacking this camera!
It works well for me most of the time, though i'm experiencing some weird issue with image snapshot in high resolution when camera runs for a day or so.

I use it with Home Assistant by defining it as generic camera in such a way:

```yaml
- platform: generic
  name: Living Room Panoramic Camera
  stream_source: rtsp://192.168.2.54:554/ch0_0.h264
  still_image_url: http://192.168.2.54:8080/cgi-bin/snapshot.sh?res=high&watermark=yes
  verify_ssl: false
```

As you can see, i set res to "high".

In lovelace i define it like so:

```yaml
- aspect_ratio: 50%
  camera_view: live
  entity: camera.living_room_panoramic_camera
  type: picture-entity
```

With such a definition Home Assistant query camera's snapshot endpoint now and then when you are looking at it via UI.

After ~day camera starts showing outdated image that never change (watermark changes though and rtsp works as well). The only way to fix it is to reboot the camera.
If i switch back to "low" res, it works without any issues.

Is it a bug or just some misconfiguration on my side?

P.S.: Is there any chance to implement "mid" res suppose? Low res resolution is too small, high res is fine, but quite slow.

Regards, Alex
